/**
 * This package provides APIs required for implementing a WPS server. Classes inside com.bc.wps.api.schema
 * were generated by jaxb transformation, but some of them have been modified because the transformation did
 * not fully reflect the wps or ows schema. Some of the classes were also modified to make it easier to construct.
 */
package com.bc.wps.api;
